blank_issues_enabled: false
contact_links:
  - name: Documentación del Proyecto
    url: "https://github.com/brayandiazc/programacion-agnostica/wiki"
    about: Consulta la documentación completa del proyecto
  - name: Discusiones de la Comunidad
    url: "https://github.com/brayandiazc/programacion-agnostica/discussions"
    about: Únete a las discusiones para hacer preguntas generales
